Aggiunte lezione 2703
Augugrumi/GestioneImpreseInformaticheNotes pull request #22
Opened 2018-03-27 17:52 UTC by mzanella

**Description**
Da sistemare il nome dell'università, le percentuali e i prezzi degli esempi.

2018-03-28 09:13 UTC, Polpetta requested changes
C'è qualche robettina da cambiare

2018-03-28 09:13 UTC, Polpetta commented on res/sections/40-Lez27032018.tex
> +forniscono all'incirca 11 milioni di pezzi di informazioni al secondo, di cui
`pezzi`? Forse è meglio `stimoli`

2018-03-28 09:13 UTC, Polpetta commented on res/sections/40-Lez27032018.tex
> +\todo{sistemare percentuali}
?

2018-03-28 09:13 UTC, Polpetta commented on res/sections/40-Lez27032018.tex
> +\todo{Sistemare prezzi}
È 448 se non sbaglio, non 450

2018-03-28 09:13 UTC, Polpetta commented on res/sections/40-Lez27032018.tex
> +rialzo massimo che sarà disposto a
Tira su `fare` nella riga che altrimenti sta da solo ed è brutto :sweat_smile:

2018-03-28 09:16 UTC, lisaparma requested changes
Cambio di sesso plz

2018-03-28 09:16 UTC, lisaparma commented on res/sections/40-Lez27032018.tex
>  La Neurobusiness è nata a seguito di un paio di evoluzioni pesanti che sono
**Il** neurobusiness  è **nato**

2018-03-28 09:19 UTC, mzanella commented on res/sections/40-Lez27032018.tex
> +forniscono all'incirca 11 milioni di pezzi di informazioni al secondo, di cui
Lascerei così poiché le informazioni non sono complemte ma vengono ricostruite dal nostro cervello

2018-03-28 09:19 UTC, mzanella commented on res/sections/40-Lez27032018.tex
> +\todo{sistemare percentuali}
Confrontare con le slides le percentuali

2018-03-28 09:22 UTC, mzanella commented on res/sections/40-Lez27032018.tex
> +\todo{Sistemare prezzi}
@lisaparma sa

2018-03-29 14:14 UTC, EmanueleC reviewed
Sono per la maggior parte refusi :)

2018-03-29 14:14 UTC, EmanueleC commented on res/sections/40-Lez27032018.tex
> +le partite di basket della squadra dell'università del Vattelaapesca\todo
Duke University

2018-03-29 14:16 UTC, EmanueleC commented on res/sections/40-Lez27032018.tex
> +sempre così razionale?
razional**i**

2018-03-29 14:17 UTC, EmanueleC commented on res/sections/40-Lez27032018.tex
> +differenze di ogni singolo individuo, è generalizzato dall'\textit{homo
è generalizzat**a**

2018-03-29 14:17 UTC, EmanueleC commented on res/sections/40-Lez27032018.tex
> +La seconda parte, il \textit{mid brain}, si occupa delle le emozioni: emozioni
delle  ~~le~~ (togliere le)

2018-03-29 14:18 UTC, EmanueleC commented on res/sections/40-Lez27032018.tex
> +bisogno, spesso, ti reazioni più veloci: per gli atleti spesso è indispensabile
**di** reazioni

2018-03-29 15:21 UTC, mdipirro commented on res/sections/40-Lez27032018.tex
> +forniscono all'incirca 11 milioni di pezzi di informazioni al secondo, di cui
Perché non "frammenti"? Suona bene secondo me

2018-03-29 15:24 UTC, mzanella commented on res/sections/40-Lez27032018.tex
> +forniscono all'incirca 11 milioni di pezzi di informazioni al secondo, di cui
Fatto

2018-03-29 15:30 UTC, mdipirro approved these changes
Ho fatto dei piccoli cambiamenti e corretto un paio di typo. Non mi sono tirato giù le percentuali e il nome dell'università, ma a memoria mi sembrano ok e comunque non sono fondamentali per capire il senso

2018-03-29 15:39 UTC, merged