Aggiunte lez28032018
Augugrumi/GestioneImpreseInformaticheNotes pull request #26
Opened 2018-03-29 17:02 UTC by mzanella

**Reference to the issue (if any)**: closes #

**Description**

2018-03-29 18:31 UTC, EmanueleC commented
C'era un branch lezione2803 già fatto per questo 😨 ... vabbeH vediamo se riusciamo a mettere insieme le correzioni 😃 😄 @Polpetta

2018-03-29 19:34 UTC, mzanella commented
Wat jammer... Ero sicuro non ci fossero altri branch quando ho iniziato il lavoro

2018-04-01 17:24 UTC, Polpetta requested changes
Il contenuto è ok, ci sono delle inesattezze coi tempi verbali e delle parentesi non chiuse :grin:

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +non venne spiegata la differenza tra le birre, mentre al secondo sì. Il
`I` non `Il`

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +risultati dicono che il primo gruppo scelse la birra con l'aceto, il secondo la
Devi fare tutta la frase al passato o non sta in piedi altrimenti! Usa `mostrarono` al posto di `dicono`

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +L'esperimento è poi proseguito aggiungendo un terzo gruppo, al quale la
`proseguì`: è un'azione conclusa nel tempo e che è avvenuta una sola volta

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +differenza tra le 2 caraffe di birra è stata spiegata dopo l'assaggio, ma
`fu` al posto di `è stata`

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +piacque con l'aceto.
Eh? Io scriverei `scelse la birra contenente l'aceto` (a meno che tu non ti sia dimenticato un pezzo di frase in giro :sweat_smile: )

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +Tale esperimento dimostra quindi che l'aspettativa aveva modificato
Io userei anche `modifica`, però vedi te se quale ti piace di più

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +diverse. Anche le etichette del cibo lavorano in questa maniera: più creano una
Che intendi per `etichette`? :thinking:

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +persone. Anche per questo, negli ultimi anni, è nato il \textbf{self-branding}, ovvero la gestione di se\' stessi e della propria reputazione come fosse un brand. A questo sono strettamente legate tu
80 colonne

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +ragionata e quindi che lavora sul new brain)m, che può essere per esempio la
- Hai chiuso una parentesi che non è mai stata aperta
- C'è una `m` di troppo

2018-04-01 17:24 UTC, Polpetta commented on res/sections/45-Lez28032018.tex
> +sempre la parte emozionale su quella razionale, in quanto gli aspetti del mid
C'è un doppio `in quanto`

2018-04-03 09:53 UTC, Polpetta approved these changes
Ora è ok :ok_hand:

2018-04-03 09:56 UTC, merged