Little changes lez 1704
Augugrumi/GestioneImpreseInformaticheNotes pull request #31
Opened 2018-04-18 07:26 UTC by mzanella

**Reference to the issue (if any)**: closes #

**Description**

2018-04-18 08:18 UTC, Polpetta requested changes
Ci sono degli errori di sbaglio, il resto è ok :ok_hand:

2018-04-18 08:18 UTC, Polpetta commented on res/sections/60-Lez17042018.tex
> +venga portato a termine. Alcuni esempi le aziende che creano prodotti
Metti `Per esempio` al posto di `Alcuni esempi` :sweat_smile:

2018-04-18 08:18 UTC, Polpetta commented on res/sections/60-Lez17042018.tex
> +appunto i consulenti. In quest'ultimo caso, nella maggior parte dei casi, la
Eh? Sta frase non ha molto senso :thinking:

2018-04-18 08:18 UTC, Polpetta commented on res/sections/60-Lez17042018.tex
> +appunto i consulenti. In quest'ultimo caso, nella maggior parte dei casi, la
`In quest'ultimo caso, nella maggior parte dei casi` anche qui togli una delle due altrimenti è super ripetitivo :sweat_smile:

2018-04-18 08:18 UTC, Polpetta commented on res/sections/60-Lez17042018.tex
> +\textbf{polarizzazione} che ho portato all'inversione di questa curva
`ho` -> `ha`

2018-04-18 08:18 UTC, Polpetta commented on res/sections/60-Lez17042018.tex
> +preferiscono uso di prodotto low-cost in alcuni settori, mentre in altri si
`preferisce l'uso di prodotti low-cost` senza `in alcuni settori` che altrimenti diventa una ripetizione

2018-04-19 12:16 UTC, Polpetta approved these changes

2018-04-19 13:45 UTC, lisaparma approved these changes

2018-04-22 11:01 UTC, Polpetta commented
@mzanella ci sono ancora degli orrori ortografici!

2018-04-22 11:12 UTC, mzanella commented
Si ma sono sulla lezione del 18

2018-04-23 07:37 UTC, Polpetta commented
La mergio, gli errori sono corretti in #32

2018-04-23 07:37 UTC, merged