Fix lezione 0703
Augugrumi/GestioneImpreseInformaticheNotes pull request #8
Opened 2018-03-09 15:37 UTC by mzanella

**Reference to the issue (if any)**: #

**Description**

2018-03-10 11:13 UTC, Polpetta commented
@mzanella Hai per caso mergiato qualche altro branch su questo? Perché il contenuto mi pare uguale a #4, e difatti ci sono dei conflitti :thinking:  (che con il `dictionary` è ok, ma con la lezione mi par strano)

2018-03-10 11:20 UTC, mzanella commented
Probabilmente ho fatto un po' di casino adesso sistemo visto che hai accettato l'altra PR

2018-03-10 11:29 UTC, Polpetta commented
Ook!

2018-03-10 13:55 UTC, Polpetta requested changes
Ci son delle robe da sistemare! Non son molte, più che altro per redere il testo più leggilbile

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> +\\
Eviterei di mettere i `\\`, lo sai anche tu che non è buona pratica :sweat_smile:

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> +Le idee delle startup sono spesso caratterizzate avere una grossa opportunità,
Teniamo `start-up` o `startup`?

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + tempi ristretti: un errore di molta start-up è voler uscire con un prodotto
`molte`, non `molta`

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + interessati. Ciò è fondamentale in quanto approcciandosi ad aree nuove di
Riscriverei questa frase con:
`Lo scopo di un MVP è di ottenere sia un feedback dal mercato sia un'avvicinamento di eventuali clienti interessati`

Però sta in piedi anche così, quindi sei libero di non cambiarla :grin:

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + mercato è importante ottenere delle giuste direzione di mercato. Nel caso in
Ripetizione di `mercato`. Alla fine scrivi `giuste direzioni dello stesso`

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + cui il mercato indichi che la direzione di mercato scelta è errata è
`mercato` -> `esso`

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + I \textbf{co-working} sono dei luoghi, strutture e ambienti che messi a
Togli il `che` o la frase non sta su :sweat_smile:

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + spesso entrare in contatto con altre start-up dove idee potrebbero venire
io metterei `in cui è possibile sviluppare, lavorare e, molto spesso, entrare in contatto con`. Però vedi te quale ti suona meglio come frase!

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + aziende alla fin fine hanno sempre gli stessi problemi e è utile sapere come
`ed è`

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + tanto più quanto più tempo rimani al suo interno, nel modello americano il
`tanto più si rimane al suo interno` secondo me è più facile da leggere

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + \todo{Non ha detto nient'altro a riguardo!}
Cancella sto TODO che non serve ormai :sweat_smile:

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + anche se possono continuare a essere considerate azionisti di maggioranza.
`considerati`, stiamo parlando dei founders no?

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + fase \textbf{early}) si ha la dimostrazione che la start-up sta cominciando a
Manca la parentesi d'apertura, `(`

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> + Business Angels un business angel in Italia investe dai 10.000 ai
io metterei i due punti dopo `Business Angels`.
Tipo:
```
Business Angels: in Italia investe
...
```

2018-03-10 13:55 UTC, Polpetta commented on res/sections/25-Lez07032018.tex
> +vantaggiosa possono decidere di vendere anche le quote anche dei fondatori che
C'è un doppio `anche` qui

2018-03-11 10:12 UTC, mzanella commented on res/sections/25-Lez07032018.tex
> +Le idee delle startup sono spesso caratterizzate avere una grossa opportunità,
Bho https://en.wikipedia.org/wiki/Startup_company

2018-03-13 12:01 UTC, lisaparma submitted a review, later dismissed

2018-03-13 12:31 UTC, lisaparma requested changes
Errore ortografico

2018-03-13 12:31 UTC, lisaparma commented on dictionary.it.pws
> +un'avvicinamento
giusto "un avvicinamento" senza apostrofo

2018-03-13 12:43 UTC, mzanella commented
Sisi lo so che ho fatto una cagata

2018-03-13 16:25 UTC, merged